### ISSUE TITLE
Open Source Noob > helpful AMD addition. 

### ISSUE THREAD

**Issue by dylan-baskind** [jamsyoung/dust-compiler#14]
Hi there James,

Thanks for this little guy, works nicely.

I'm a pretty new to open source contributions (pull requests etc), so I thought I'd just post this code suggestion manually.

I use RequireJS for modularity / dependency etc --- so I needed these compiled templates to be output AMD style.

Added this around line 111:

```
                    // Wrap in AMD tags...
                    data = "define(['dust'], function(){ dust = require('dust'); " + data + "});";
```

Probably a more elegant way to do it than that and probably makes more sense to have a switch on the command line for AMD, rather than its current always-AMD. 

Anyway, perhaps you'll find it useful (*or if others might), if they run into a similar issue with RequireJS & these compiled templates.

Cheers!

**Comment by jamsyoung** [comment]
Thanks for the feedback!  I am looking into integrating this as a command line argument.

**Comment by jamsyoung** [comment]
Well, it took me 3 months to get around to doing this, but I got it done.

**Comment by dylan-baskind** [comment]
You're a legend! 

(I've been hacking at the source each time I update via Bower, so this'll be a great workflow addition for me).

Thanks for the project - I love using it!

**Comment by jamsyoung** [comment]
No problem.  I'll get it merged in and pushed up to npm very soon.  If you have any problems let me know.
Thanks
