### ISSUE TITLE
Package.json ("dust-compiler.js" >> "dust-compiler-cli.js")

### ISSUE THREAD

**Issue by dylan-baskind** [jamsyoung/dust-compiler#26]
Hey there James,

I'm fairly newb when it comes to NPM, but I'm fairly sure you've got an error in your package.json --- when I tried installing the package via NPM (npm install -g dust-compiler) I keep getting an ENOENT error when it tries to chmod dust-compiler.js (which doesn't seem to exist at the top level of the directory).

Eventually downloaded the git repo, altered the package.json to look for "dust-compiler-cli.js" instead of "dust-compiler.js", and got it working by pointing NPM at this local repo.

(Might be a weird thing with my own NPM setup, since I've installed Node + NPM through homebrew - but hopefully a helpful tip, if anyone else runs into a similar error!).

Cheers,

Dylan.

**Comment by jamsyoung** [comment]
You nailed it, I didn't properly update the new filename in the package.json.

Thanks
