### ISSUE TITLE
Concatenated filenames in compile.js

### ISSUE THREAD

**Issue by dylan-baskind** [jamsyoung/dust-compiler#27]
(Sorry for spamming the issues, but finding some errors post-update).

In compile.js:

```
source = path.normalize(sourcePath + sourceFilename);
```

Seems to double up the dir path (i.e. source ends up as: "some/dir/path/some/dir/path/filename.js).

I had to do:

```
source = sourceFilename;
```

to make it work.

(Assuming whatever is passing the arguments to the function does something not-quite-right?).

Again, might be a personal setup issue, but hopefully helps some folks out.

Cheers,

D.

**Comment by jamsyoung** [comment]
Thanks for the info. I am sure it is doing something "not-quite-right". 

Which command line arguments are you passing in when you see this?

**Comment by jamsyoung** [comment]
I am not able to reproduce this. :confused: 

If you can provide the command you are running when you see this, that would be great.

OR

Pull down the latest from `master` and do the following:

```
$ . enable-debug.conf
```

before running 

```
$ ./dust-compiler-cli.js [your arguments]
```

This should show a bunch of debug info in your console.  I am interested in the last 2 `compile` lines before a `Compiled` line is output.  Here is an example:

```
$ ./dust-compiler-cli.js -s test/mock/ -d . --bootstrap --includepath
  log-notify setting notifier to terminal-notifier +0ms
  compile compile called with options: test.js, test/mock/, ./, {"_":[],"s":"test/mock/","source":"test/mock/","d":".","destination":".","bootstrap":true,"includepath":true,"$0":"node ./dust-compiler-cli.js","nonotify":false,"amd":false} +0ms
  compile composited source: test/mock/test.js +0ms
Compiled test/mock/test.dust as test/mock/test
```

**Comment by andrewwakeling** [comment]
+1.

My project structure is like this:
\MYPROJECT
\MYPROJECT\tl <-- template files
\MYPROJECT\js\tl <--- where I want my compiled template files to go

Here's the output you requested:
C:\dev\MYPROJECT>dust-compiler -s tl -d js\tl

Watching tl\
Will write to js\tl\
Type ^C to cancel
  compile compile called with options: tl\hello.dust, tl\, js\tl\, {"_":[],"s":"tl","source":"tl","d":"js\tl","destination":"js\tl","$0":"node C:\Users\Zak\
\AppData\Roaming\npm\node_modules\dust-compiler\dust-compiler-cli.js","includepath":false,"nonotify":false,"amd":false} +0ms
  compile composited source: tl\tl\hello.dust +2ms
ERROR: fs.stat: ENOENT, stat 'C:\dev\MYPROJECT\tl\tl\hello.dust'

I'm also getting problems with the output directory. Getting the same problem regardless of whether I am using a relative path or a full path.

**Comment by aaronsnow** [comment]
I'm seeing this doubled-path problem too. (I'm on MacOS 10.9.1 FWIW.)

I've noticed this problem _doesn't_ happen when I use the `--bootstrap` flag.  But here's what I'm seeing without the flag:

```
devbox: dust-compiler -s assets/dust-src -d assets/dust-compiled 
Watching assets/dust-src/
Will write to assets/dust-compiled/
Type ^C to cancel
ERROR: fs.stat: ENOENT, stat 'assets/dust-src/assets/dust-src/result.dust'

/usr/local/lib/node_modules/dust-compiler/lib/compile.js:39
                throw error;
                      ^
Error: ENOENT, stat 'assets/dust-src/assets/dust-src/result.dust'
```

Like andrewwakeling, I get the error whether I use relative or absolute paths.

**Comment by aaronsnow** [comment]
The problem appears to be that sourceFilename already includes a path. The fix that seems to be working great for me is at line 19, change:

```
    sourceFilename = sourceFilename || '';
```

to

```
    sourceFilename = path.basename(sourceFilename) || '';
```

I'll put in a pull request to this effect.
