### ISSUE TITLE
Document that templates need to have the extension ".dust"

### ISSUE THREAD

**Issue by andrewwakeling** [jamsyoung/dust-compiler#30]
Even though the extension for dust templates is documented as ".dust", there seems to be some people using the ".tl" template. (I have an issue with the dust project here: https://github.com/linkedin/dustjs/issues/370 )

I have noticed in the code, that you're explicitly looking for a ".dust" extension. Can you please just add that templates must be called .dust in the documentation? Thanks!

**Comment by jamsyoung** [comment]
Yes.  Thanks for the info.  I will get this, and other open issues addressed soon-ish :)
